
obj-m += ls3.o
CONFIG_MODULE_SIG=n

# Allow newer features of C, like declaring a variable inside a for-loop,
# or declaring variables in the middle of a function.
ccflags-y=-std=gnu99 -Wno-declaration-after-statement -Werror
